/* imports.c -- GENERATED by runtime/tools/gen_imports.py; do not edit.
 *
 * Every import of libassissinscreed that no loaded module
 * exports (gl* aside: the GL layer serves those), mapped to the host
 * function or object that serves it: b_* shims for the bionic ABI
 * (bionic_*.c, android_ndk.c, gl_*.c, the port's files), and newlib
 * directly where the two ABIs agree. Declared through asm labels so no
 * C prototype is needed (or can conflict): only the address is taken
 * here. The search over the table is the runtime's imports_lookup.c.
 *
 * Weak imports bound to NULL on purpose: none.
 * MIT.
 */
#include "imports.h"

extern const char sym___aeabi_d2f[] __asm__("__aeabi_d2f");
extern const char sym___aeabi_d2iz[] __asm__("__aeabi_d2iz");
extern const char sym___aeabi_d2lz[] __asm__("__aeabi_d2lz");
extern const char sym___aeabi_dadd[] __asm__("__aeabi_dadd");
extern const char sym___aeabi_ddiv[] __asm__("__aeabi_ddiv");
extern const char sym___aeabi_dmul[] __asm__("__aeabi_dmul");
extern const char sym___aeabi_dsub[] __asm__("__aeabi_dsub");
extern const char sym___aeabi_f2d[] __asm__("__aeabi_f2d");
extern const char sym___aeabi_f2iz[] __asm__("__aeabi_f2iz");
extern const char sym___aeabi_fadd[] __asm__("__aeabi_fadd");
extern const char sym___aeabi_fcmpeq[] __asm__("__aeabi_fcmpeq");
extern const char sym___aeabi_fcmpge[] __asm__("__aeabi_fcmpge");
extern const char sym___aeabi_fcmpgt[] __asm__("__aeabi_fcmpgt");
extern const char sym___aeabi_fcmple[] __asm__("__aeabi_fcmple");
extern const char sym___aeabi_fcmplt[] __asm__("__aeabi_fcmplt");
extern const char sym___aeabi_fdiv[] __asm__("__aeabi_fdiv");
extern const char sym___aeabi_fmul[] __asm__("__aeabi_fmul");
extern const char sym___aeabi_fsub[] __asm__("__aeabi_fsub");
extern const char sym___aeabi_i2d[] __asm__("__aeabi_i2d");
extern const char sym___aeabi_i2f[] __asm__("__aeabi_i2f");
extern const char sym___aeabi_idiv[] __asm__("__aeabi_idiv");
extern const char sym___aeabi_idivmod[] __asm__("__aeabi_idivmod");
extern const char sym___aeabi_l2d[] __asm__("__aeabi_l2d");
extern const char sym___aeabi_ldivmod[] __asm__("__aeabi_ldivmod");
extern const char sym___aeabi_lmul[] __asm__("__aeabi_lmul");
extern const char sym___aeabi_ui2d[] __asm__("__aeabi_ui2d");
extern const char sym___aeabi_ui2f[] __asm__("__aeabi_ui2f");
extern const char sym___aeabi_uidiv[] __asm__("__aeabi_uidiv");
extern const char sym___aeabi_uidivmod[] __asm__("__aeabi_uidivmod");
extern const char sym___aeabi_unwind_cpp_pr0[] __asm__("__aeabi_unwind_cpp_pr0");
extern const char sym___aeabi_unwind_cpp_pr1[] __asm__("__aeabi_unwind_cpp_pr1");
extern const char sym_atan[] __asm__("atan");
extern const char sym_b___android_log_write[] __asm__("b___android_log_write");
extern const char sym_b___cxa_pure_virtual[] __asm__("b___cxa_pure_virtual");
extern const char sym_b___stack_chk_fail[] __asm__("b___stack_chk_fail");
extern const char sym_b___stack_chk_guard[] __asm__("b___stack_chk_guard");
extern const char sym_b_exit[] __asm__("b_exit");
extern const char sym_b_fclose[] __asm__("b_fclose");
extern const char sym_b_fflush[] __asm__("b_fflush");
extern const char sym_b_fopen[] __asm__("b_fopen");
extern const char sym_b_fread[] __asm__("b_fread");
extern const char sym_b_fseek[] __asm__("b_fseek");
extern const char sym_b_ftell[] __asm__("b_ftell");
extern const char sym_b_fwrite[] __asm__("b_fwrite");
extern const char sym_b_gettimeofday[] __asm__("b_gettimeofday");
extern const char sym_b_memcpy[] __asm__("b_memcpy");
extern const char sym_b_memmove[] __asm__("b_memmove");
extern const char sym_b_memset[] __asm__("b_memset");
extern const char sym_b_printf[] __asm__("b_printf");
extern const char sym_b_pthread_mutex_lock[] __asm__("b_pthread_mutex_lock");
extern const char sym_b_pthread_mutex_unlock[] __asm__("b_pthread_mutex_unlock");
extern const char sym_b_puts[] __asm__("b_puts");
extern const char sym_b_remove[] __asm__("b_remove");
extern const char sym_b_sprintf[] __asm__("b_sprintf");
extern const char sym_b_sqrt[] __asm__("b_sqrt");
extern const char sym_b_vsprintf[] __asm__("b_vsprintf");
extern const char sym_cos[] __asm__("cos");
extern const char sym_free[] __asm__("free");
extern const char sym_lrand48[] __asm__("lrand48");
extern const char sym_malloc[] __asm__("malloc");
extern const char sym_memcmp[] __asm__("memcmp");
extern const char sym_sin[] __asm__("sin");
extern const char sym_strcat[] __asm__("strcat");
extern const char sym_strlen[] __asm__("strlen");
extern const char sym_tanf[] __asm__("tanf");

DynLibFunction dcr_imports[] = {
    {"__aeabi_d2f", (uintptr_t)sym___aeabi_d2f},
    {"__aeabi_d2iz", (uintptr_t)sym___aeabi_d2iz},
    {"__aeabi_d2lz", (uintptr_t)sym___aeabi_d2lz},
    {"__aeabi_dadd", (uintptr_t)sym___aeabi_dadd},
    {"__aeabi_ddiv", (uintptr_t)sym___aeabi_ddiv},
    {"__aeabi_dmul", (uintptr_t)sym___aeabi_dmul},
    {"__aeabi_dsub", (uintptr_t)sym___aeabi_dsub},
    {"__aeabi_f2d", (uintptr_t)sym___aeabi_f2d},
    {"__aeabi_f2iz", (uintptr_t)sym___aeabi_f2iz},
    {"__aeabi_fadd", (uintptr_t)sym___aeabi_fadd},
    {"__aeabi_fcmpeq", (uintptr_t)sym___aeabi_fcmpeq},
    {"__aeabi_fcmpge", (uintptr_t)sym___aeabi_fcmpge},
    {"__aeabi_fcmpgt", (uintptr_t)sym___aeabi_fcmpgt},
    {"__aeabi_fcmple", (uintptr_t)sym___aeabi_fcmple},
    {"__aeabi_fcmplt", (uintptr_t)sym___aeabi_fcmplt},
    {"__aeabi_fdiv", (uintptr_t)sym___aeabi_fdiv},
    {"__aeabi_fmul", (uintptr_t)sym___aeabi_fmul},
    {"__aeabi_fsub", (uintptr_t)sym___aeabi_fsub},
    {"__aeabi_i2d", (uintptr_t)sym___aeabi_i2d},
    {"__aeabi_i2f", (uintptr_t)sym___aeabi_i2f},
    {"__aeabi_idiv", (uintptr_t)sym___aeabi_idiv},
    {"__aeabi_idivmod", (uintptr_t)sym___aeabi_idivmod},
    {"__aeabi_l2d", (uintptr_t)sym___aeabi_l2d},
    {"__aeabi_ldivmod", (uintptr_t)sym___aeabi_ldivmod},
    {"__aeabi_lmul", (uintptr_t)sym___aeabi_lmul},
    {"__aeabi_ui2d", (uintptr_t)sym___aeabi_ui2d},
    {"__aeabi_ui2f", (uintptr_t)sym___aeabi_ui2f},
    {"__aeabi_uidiv", (uintptr_t)sym___aeabi_uidiv},
    {"__aeabi_uidivmod", (uintptr_t)sym___aeabi_uidivmod},
    {"__aeabi_unwind_cpp_pr0", (uintptr_t)sym___aeabi_unwind_cpp_pr0},
    {"__aeabi_unwind_cpp_pr1", (uintptr_t)sym___aeabi_unwind_cpp_pr1},
    {"__android_log_write", (uintptr_t)sym_b___android_log_write},
    {"__cxa_pure_virtual", (uintptr_t)sym_b___cxa_pure_virtual},
    {"__stack_chk_fail", (uintptr_t)sym_b___stack_chk_fail},
    {"__stack_chk_guard", (uintptr_t)sym_b___stack_chk_guard},
    {"atan", (uintptr_t)sym_atan},
    {"cos", (uintptr_t)sym_cos},
    {"exit", (uintptr_t)sym_b_exit},
    {"fclose", (uintptr_t)sym_b_fclose},
    {"fflush", (uintptr_t)sym_b_fflush},
    {"fopen", (uintptr_t)sym_b_fopen},
    {"fread", (uintptr_t)sym_b_fread},
    {"free", (uintptr_t)sym_free},
    {"fseek", (uintptr_t)sym_b_fseek},
    {"ftell", (uintptr_t)sym_b_ftell},
    {"fwrite", (uintptr_t)sym_b_fwrite},
    {"gettimeofday", (uintptr_t)sym_b_gettimeofday},
    {"lrand48", (uintptr_t)sym_lrand48},
    {"malloc", (uintptr_t)sym_malloc},
    {"memcmp", (uintptr_t)sym_memcmp},
    {"memcpy", (uintptr_t)sym_b_memcpy},
    {"memmove", (uintptr_t)sym_b_memmove},
    {"memset", (uintptr_t)sym_b_memset},
    {"printf", (uintptr_t)sym_b_printf},
    {"pthread_mutex_lock", (uintptr_t)sym_b_pthread_mutex_lock},
    {"pthread_mutex_unlock", (uintptr_t)sym_b_pthread_mutex_unlock},
    {"puts", (uintptr_t)sym_b_puts},
    {"remove", (uintptr_t)sym_b_remove},
    {"sin", (uintptr_t)sym_sin},
    {"sprintf", (uintptr_t)sym_b_sprintf},
    {"sqrt", (uintptr_t)sym_b_sqrt},
    {"strcat", (uintptr_t)sym_strcat},
    {"strlen", (uintptr_t)sym_strlen},
    {"tanf", (uintptr_t)sym_tanf},
    {"vsprintf", (uintptr_t)sym_b_vsprintf},
    {"", 0},
};

int dcr_imports_count = (int)(sizeof(dcr_imports) / sizeof(dcr_imports[0])) - 1;
